version: '3.7'

services:
  web:
    build: ./MiniYT
    command: bash -c "chmod +x ./start.sh && ./start.sh"
    volumes:
      - ./MiniYT/:/usr/src/MiniYT/
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aks
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=PYT

volumes:
  postgres_data: