# Generated by Django 2.2 on 2020-04-27 11:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetchAPI', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoId', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('publishedAt', models.DateTimeField()),
                ('thumbnailURL', models.URLField()),
                ('searchvector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['searchvector'], name='data_video_searchv_975a5c_gin'),
        ),
    ]
