# Generated by Django 2.2 on 2020-04-26 17:25

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_migration_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='searchVector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
