# Generated by Django 2.2 on 2020-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_migration_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetchAPI', models.BooleanField(default=False)),
            ],
        ),
    ]
